#!/usr/bin/env ruby

numbers = []
$stdin.each do |line|
  next if line =~ /^\s*#/
  line = line.strip
  next if line.empty?
  numbers << line.to_f
end

average = numbers.inject(&:+) / numbers.count
standard_deviation = Math.sqrt(numbers.map { |number| (number-average)*(number-average) }.inject(&:+) / numbers.count)
puts numbers.find_all { |number| (number-average).abs <= standard_deviation }.join("\n")

